[build]
  functions = "netlify/functions"
  publish = "main"

[[redirects]]
  from = "/.netlify/functions/*"
  to = "https://dps-carnival-registration.onrender.com/.netlify/functions/:splat"
  status = 200

[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type"
    Access-Control-Allow-Methods = "GET,POST,DELETE,OPTIONS"

[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/main/index.html"
  status = 200
