services:
  - type: web
    name: dps-carnival-registration
    env: python
    runtime: python3
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    autoDeploy: true
    region: oregon
    plan: free
    envVars:
      - key: DATABASE_URL
        value: ""
